"""Add encryption support for files and users

Revision ID: f9b923eed535
Revises: 39854d26cbdd
Create Date: 2025-11-06 03:18:38.104670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b923eed535'
down_revision = '39854d26cbdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('encrypted_data', sa.LargeBinary(), nullable=True))
    op.add_column('files', sa.Column('encrypted_key', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('encryption_metadata', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('is_encrypted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('public_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('private_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('key_salt', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('key_created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'key_created_at')
    op.drop_column('users', 'key_salt')
    op.drop_column('users', 'private_key')
    op.drop_column('users', 'public_key')
    op.drop_column('files', 'is_encrypted')
    op.drop_column('files', 'encryption_metadata')
    op.drop_column('files', 'encrypted_key')
    op.drop_column('files', 'encrypted_data')
    # ### end Alembic commands ###
