// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQZ3vis0_7xmDiLhDAr-TmD8zJFrf1PLg',
    appId: '1:785722200056:web:2fb5043f400d5d3321900d',
    messagingSenderId: '785722200056',
    projectId: 'taxease-ec35f',
    authDomain: 'taxease-ec35f.firebaseapp.com',
    storageBucket: 'taxease-ec35f.firebasestorage.app',
    measurementId: 'G-SNYLF4E7HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcgvx5ISvgw2R6_DFgt6PJSnQHU4j0k8A',
    appId: '1:785722200056:android:c81130658bd70caa21900d',
    messagingSenderId: '785722200056',
    projectId: 'taxease-ec35f',
    storageBucket: 'taxease-ec35f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZ3J69Xf0Jwl9u6zs65gAVGnXFQ7m6LQ',
    appId: '1:785722200056:ios:a8eff24c1073f74e21900d',
    messagingSenderId: '785722200056',
    projectId: 'taxease-ec35f',
    storageBucket: 'taxease-ec35f.firebasestorage.app',
    iosClientId: '785722200056-i00rhgh5oueo1od90h3qcgvheb77e0bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxEase',
  );

}