"""Add comprehensive T1 tax form models

Revision ID: 68aa2ca60ef1
Revises: f9b923eed535
Create Date: 2025-11-07 00:36:01.301934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68aa2ca60ef1'
down_revision = 'f9b923eed535'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t1_personal_forms', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('t1_personal_forms', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('t1_personal_forms', sa.Column('address', sa.Text(), nullable=False))
    op.add_column('t1_personal_forms', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('t1_personal_forms', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('t1_personal_forms', sa.Column('is_canadian_citizen', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('has_foreign_property', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('has_medical_expenses', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('has_charitable_donations', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('has_moving_expenses', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('is_self_employed', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('is_first_home_buyer', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('sold_property_long_term', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('sold_property_short_term', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('has_work_from_home_expense', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('was_student_last_year', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('is_union_member', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('has_daycare_expenses', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('is_first_time_filer', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('has_other_income', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('other_income_description', sa.Text(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('has_professional_dues', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('has_rrsp_fhsa_investment', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('has_child_art_sport_credit', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('is_province_filer', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('moving_expense_for_individual', sa.Boolean(), nullable=True))
    op.add_column('t1_personal_forms', sa.Column('moving_expense_for_spouse', sa.Boolean(), nullable=True))
    op.alter_column('t1_personal_forms', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('t1_personal_forms', 'sin',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=9),
               nullable=False)
    op.alter_column('t1_personal_forms', 'marital_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.drop_column('t1_personal_forms', 'charitable_donations')
    op.drop_column('t1_personal_forms', 'investment_income')
    op.drop_column('t1_personal_forms', 'total_tax')
    op.drop_column('t1_personal_forms', 'rrsp_contributions')
    op.drop_column('t1_personal_forms', 'employment_income')
    op.drop_column('t1_personal_forms', 'tax_year')
    op.drop_column('t1_personal_forms', 'provincial_tax')
    op.drop_column('t1_personal_forms', 'federal_tax')
    op.drop_column('t1_personal_forms', 'refund_or_owing')
    op.drop_column('t1_personal_forms', 'total_income')
    op.drop_column('t1_personal_forms', 'self_employment_income')
    op.drop_column('t1_personal_forms', 'other_income')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t1_personal_forms', sa.Column('other_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t1_personal_forms', sa.Column('self_employment_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t1_personal_forms', sa.Column('total_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t1_personal_forms', sa.Column('refund_or_owing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t1_personal_forms', sa.Column('federal_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t1_personal_forms', sa.Column('provincial_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t1_personal_forms', sa.Column('tax_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('t1_personal_forms', sa.Column('employment_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t1_personal_forms', sa.Column('rrsp_contributions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t1_personal_forms', sa.Column('total_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t1_personal_forms', sa.Column('investment_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t1_personal_forms', sa.Column('charitable_donations', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('t1_personal_forms', 'marital_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('t1_personal_forms', 'sin',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('t1_personal_forms', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('t1_personal_forms', 'moving_expense_for_spouse')
    op.drop_column('t1_personal_forms', 'moving_expense_for_individual')
    op.drop_column('t1_personal_forms', 'is_province_filer')
    op.drop_column('t1_personal_forms', 'has_child_art_sport_credit')
    op.drop_column('t1_personal_forms', 'has_rrsp_fhsa_investment')
    op.drop_column('t1_personal_forms', 'has_professional_dues')
    op.drop_column('t1_personal_forms', 'other_income_description')
    op.drop_column('t1_personal_forms', 'has_other_income')
    op.drop_column('t1_personal_forms', 'is_first_time_filer')
    op.drop_column('t1_personal_forms', 'has_daycare_expenses')
    op.drop_column('t1_personal_forms', 'is_union_member')
    op.drop_column('t1_personal_forms', 'was_student_last_year')
    op.drop_column('t1_personal_forms', 'has_work_from_home_expense')
    op.drop_column('t1_personal_forms', 'sold_property_short_term')
    op.drop_column('t1_personal_forms', 'sold_property_long_term')
    op.drop_column('t1_personal_forms', 'is_first_home_buyer')
    op.drop_column('t1_personal_forms', 'is_self_employed')
    op.drop_column('t1_personal_forms', 'has_moving_expenses')
    op.drop_column('t1_personal_forms', 'has_charitable_donations')
    op.drop_column('t1_personal_forms', 'has_medical_expenses')
    op.drop_column('t1_personal_forms', 'has_foreign_property')
    op.drop_column('t1_personal_forms', 'is_canadian_citizen')
    op.drop_column('t1_personal_forms', 'email')
    op.drop_column('t1_personal_forms', 'phone_number')
    op.drop_column('t1_personal_forms', 'address')
    op.drop_column('t1_personal_forms', 'last_name')
    op.drop_column('t1_personal_forms', 'middle_name')
    op.drop_column('t1_personal_forms', 'first_name')
    # ### end Alembic commands ###
